Adding question banks
atomicjolt/senkyoshi pull request #38
Opened 2017-01-06 19:10 UTC by kamijean

2017-01-07 00:11 UTC, conradbeach requested changes
I had a few suggestions, but overall these changes look good.

It doesn't look like it's working quite right though. When I tested with course "AU014_16BC.Summer.2016", the quizzes and question banks were created correctly, but the quizzes that were supposed to include questions from the question banks had no questions in them.

[This quiz](https://au.openlmshost.com/courses/1120/quizzes/7078) is an example. It should have a number of questions from multiple quiz banks but it has 0 questions.

2017-01-07 00:11 UTC, conradbeach commented on lib/senkyoshi/models/question_bank.rb
> +        question.material.strip!
Maybe a comment here to explain the purpose of these `gsub`s would be helpful.

2017-01-07 00:11 UTC, conradbeach commented on spec/models/qti_spec.rb
> +        assert_equal (@assessment.is_a? Object), true
This assertion will always be true. `nil` and `false` are both instances of `Object`.

I would just use `assert(@assessment)` if you want to test if it got set to something.

2017-01-07 00:11 UTC, conradbeach commented on spec/models/question_bank_spec.rb
> +        assert_equal (@question_bank.is_a? Object), true
Same thing as the above comment.

2017-01-07 00:11 UTC, conradbeach commented on spec/models/survey_spec.rb
> +        assert_equal (@survey.is_a? Object), true
Same again.

2017-01-07 00:43 UTC, bfcoder commented on lib/senkyoshi/models/question_bank.rb
> +require "byebug"
Remove me

2017-01-07 00:43 UTC, bfcoder commented on lib/senkyoshi/models/question_bank.rb
> +    def setup_question_bank(question_bank, resources)
Should probably set the description to what comes from blackboard. Similar to in qti.rb
```ruby
@description = %{
  #{description}
  #{instructions}
}
```

2017-01-07 00:43 UTC, bfcoder commented on spec/models/qti_spec.rb
> +        assert_equal (@assessment.is_a? Object), true
Could also use `assert_kind_of` too?

2017-01-07 03:56 UTC, kamijean commented on lib/senkyoshi/models/question_bank.rb
> +    def setup_question_bank(question_bank, resources)
From what I could see in Canvas doesn't have descriptions in the question banks nor does the canvas_cc gem so I am guessing it might not be useful.

2017-01-07 14:29 UTC, bfcoder commented on lib/senkyoshi/models/question_bank.rb
> +    def setup_question_bank(question_bank, resources)
ok

2017-01-09 19:19 UTC, conradbeach submitted a review, later dismissed

2017-01-09 23:42 UTC, conradbeach commented
The quizzes that were previously missing questions have the correct number of questions now. It doesn't look like those quizzes are using the question banks the way that they should yet though. Instead of selecting a set of questions randomly from the appropriate quiz bank each time you take the test, the questions in the quizzes are static.

In Blackboard, you can randomly use a specified number of questions from a question bank like this.
![image](https://cloud.githubusercontent.com/assets/6520489/21788029/d6fbc42a-d689-11e6-9747-caec9b057b0e.png)

The equivalent functionality inside Canvas is to create a question group and link it to a question bank like this.
![image](https://cloud.githubusercontent.com/assets/6520489/21788022/c3b23ef8-d689-11e6-8133-4d7fece86b24.png)

It looks like Senkyoshi is pulling the correct number of questions from the question banks at the time of .imscc creation, but the questions are static after that and they're not being dynamically pulled from the question banks when a user takes the test.

2017-01-10 18:12 UTC, bfcoder commented on lib/senkyoshi/models/qti.rb
> +        end
Should we `compact`?

2017-01-10 18:12 UTC, bfcoder commented on lib/senkyoshi/models/qti.rb
> +      item.class.to_s.include?("CanvasCc::CanvasCC::Models")
`item.is_a? CanvasCc::CanvasCC::Models`

2017-01-10 18:12 UTC, bfcoder commented on lib/senkyoshi/models/question_bank.rb
> +        tag = "<p><span size=\"2\" style=\"font-size: small;\">.</span></p>"
Consider extracting into a separate method.

2017-01-10 18:12 UTC, bfcoder commented on lib/senkyoshi/xml_parser.rb
> +          single_pre_data = { file_name: file } if single_pre_data.nil?
Consider `||=`

2017-01-10 18:12 UTC, bfcoder commented on spec/models/assessment_spec.rb
> +        assert_equal @assessment.class.name, "Senkyoshi::Assessment"
`assert_equal @assessment.is_a? Senkyoshi::Assessment`

2017-01-10 18:12 UTC, bfcoder commented on spec/models/qti_spec.rb
> +        assert_equal @assessment.class.name, "Senkyoshi::Assessment"
`assert_equal @assessment.is_a? Senkyoshi::Assessment`

2017-01-10 18:12 UTC, bfcoder commented on spec/models/question_bank_spec.rb
> +        assert_equal @question_bank.class.name, "Senkyoshi::QuestionBank"
`assert_equal @question_bank.is_a? Senkyoshi::QuestionBank`

2017-01-10 18:12 UTC, bfcoder commented on spec/models/survey_spec.rb
> +        assert_equal @survey.class.name, "Senkyoshi::Survey"
`assert_equal @survey.is_a? Senkyoshi::Survey`

2017-01-10 18:59 UTC, bfcoder commented on lib/senkyoshi/models/qti.rb
> +      @workflow_state = "available"
This actually needs to stay as `published` because it is used on the assignment which uses `published` instead of `available`

2017-01-10 18:59 UTC, bfcoder commented on lib/senkyoshi/models/question_bank.rb
> +      # This is to remove the random extra <p>.</p> included in the
Maybe move this comment outside of the method?
```ruby
##
# This is to..
##
```

2017-01-10 19:35 UTC, bfcoder approved these changes
Code looks good. Pulled down and tested and works.

2017-01-10 19:35 UTC, merged